import React from 'react';

const DashboardPage = () => {
    return (
        <div className='w-full min-h-screen bg-green-300'>
            Bro this is dahsboard
            <p className='mb-55'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam tenetur consectetur nobis nemo impedit! Corporis ipsam ad laboriosam iusto ab esse dignissimos id laudantium expedita eius ratione ipsum quod hic ullam odio dolor, officiis culpa fugiat architecto et deserunt sequi rerum iure. Voluptate, dolorem velit nihil facere deleniti exercitationem maxime non nesciunt iure, natus, adipisci repellendus odit! Eligendi qui porro cupiditate exercitationem ipsa vitae. A recusandae sequi omnis quia unde consequatur. Ratione sequi repellendus tempore, id dignissimos quod, fuga quo consequatur provident, quaerat accusantium repudiandae recusandae aliquam aspernatur esse. Corrupti unde nobis quasi vero nam repellendus et beatae qui porro?</p>
            <p className='mb-55'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam tenetur consectetur nobis nemo impedit! Corporis ipsam ad laboriosam iusto ab esse dignissimos id laudantium expedita eius ratione ipsum quod hic ullam odio dolor, officiis culpa fugiat architecto et deserunt sequi rerum iure. Voluptate, dolorem velit nihil facere deleniti exercitationem maxime non nesciunt iure, natus, adipisci repellendus odit! Eligendi qui porro cupiditate exercitationem ipsa vitae. A recusandae sequi omnis quia unde consequatur. Ratione sequi repellendus tempore, id dignissimos quod, fuga quo consequatur provident, quaerat accusantium repudiandae recusandae aliquam aspernatur esse. Corrupti unde nobis quasi vero nam repellendus et beatae qui porro?</p>
            <p className='mb-55'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam tenetur consectetur nobis nemo impedit! Corporis ipsam ad laboriosam iusto ab esse dignissimos id laudantium expedita eius ratione ipsum quod hic ullam odio dolor, officiis culpa fugiat architecto et deserunt sequi rerum iure. Voluptate, dolorem velit nihil facere deleniti exercitationem maxime non nesciunt iure, natus, adipisci repellendus odit! Eligendi qui porro cupiditate exercitationem ipsa vitae. A recusandae sequi omnis quia unde consequatur. Ratione sequi repellendus tempore, id dignissimos quod, fuga quo consequatur provident, quaerat accusantium repudiandae recusandae aliquam aspernatur esse. Corrupti unde nobis quasi vero nam repellendus et beatae qui porro?</p>
            <p className=''>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam tenetur consectetur nobis nemo impedit! Corporis ipsam ad laboriosam iusto ab esse dignissimos id laudantium expedita eius ratione ipsum quod hic ullam odio dolor, officiis culpa fugiat architecto et deserunt sequi rerum iure. Voluptate, dolorem velit nihil facere deleniti exercitationem maxime non nesciunt iure, natus, adipisci repellendus odit! Eligendi qui porro cupiditate exercitationem ipsa vitae. A recusandae sequi omnis quia unde consequatur. Ratione sequi repellendus tempore, id dignissimos quod, fuga quo consequatur provident, quaerat accusantium repudiandae recusandae aliquam aspernatur esse. Corrupti unde nobis quasi vero nam repellendus et beatae qui porro?</p>
        </div>
    );
};

export default DashboardPage;